### ISSUE TITLE
Migrate to @types/yargs from typings.json

### ISSUE THREAD

**Issue by agubler** [dojo/cli#119]
**Enhancement** 

Migrate to `@types/yargs` from yargs dependency in `typings.json`

**Comment by kitsonk** [comment]
It was discussed that this would be a breaking change across the commands, but we should go ahead and bite the bullet on this as it is frustrating the management of the commands.

**Comment by kitsonk** [comment]
Are we going to do [dojo/cli-export-project](https://github.com/dojo/cli-export-project) as well?

**Comment by agubler** [comment]
@kitsonk I can do.

**Comment by agubler** [comment]
@kitsonk have opened a pr for `dojo/cli-export-project` [here](https://github.com/dojo/cli-export-project/pull/7)

**Comment by kitsonk** [comment]
This was completed I believe.
