### ISSUE TITLE
create command

### ISSUE THREAD

**Issue by rishson** [dojo/cli#12]
Create a new application:

```
dojo create myApp

Creating 'myApp'..
Doing something..
Doing something else..

All done! 
Why not try running your new app: 
cd myApp
dojo run
```

**Comment by Tomdye** [comment]
Create command should scaffold the app and run `npm install`, `typings install` etc..
Would expect
- package.json
- typings.json
...
To be pre-populated / created

**Comment by rishson** [comment]
Agree with the above, re: running `npm i` and `typings i`.
Maybe offer a `noFetch` options, e.g. `dojo create myApp -noFetch` that generates the `package.json` and `typings.json` but doesn't install. This seems like the non-default case and create should install by default.
