### ISSUE TITLE
test command

### ISSUE THREAD

**Issue by rishson** [dojo/cli#13]
Implement the `test` command.

_Options_
None

_Purpose_
Runs all tests that have been created for a dojo application and outputs the results.

```
dojo test

Running tests..
Test results:

[test results go here]
```

**Comment by agubler** [comment]
Will this include coverage concerns or purely testing? Does it include functional tests too?

**Comment by rishson** [comment]
Would be nice in the future if you could get `test` to create empty tests:

```
dojo test crete someModule
```

**Comment by rishson** [comment]
@agubler good questions. Maybe `test` runs everything, whereas `test unit` only runs unit tests and `test functional` runs functional, `test coverage` runs coverage...?

**Comment by rishson** [comment]
Might also need a `--no-return-code` option to always return `0` even if there are failed tests (IIRC, Jenkins likes runners to only return `1` if the runner hits runtime errors..)

**Comment by matt-gadd** [comment]
@rishson @agubler we should look at the intern-cli and what it exposes as we're likely to hook into it at some level.

**Comment by dylans** [comment]
Alpha of cli test had landed...
