### ISSUE TITLE
Remove default command when more than one exists

### ISSUE THREAD

**Issue by tomdye** [dojo/cli#138]
**Enhancement** 

The notion of having a default command per group when more than one command exists should be removed. As we move forward and likely create `cli-create-app` and `cli-create-widget` etc.. we should not support a default command when both exist as it may provide undesireable results for the end user. When only one is installed, however, (most cases) the default command is acceptable.

When more than one command exists for the given group, the user should be shown the help for the installed commands.

**Comment by kitsonk** [comment]
Doesn't feel like this needs to be discussed... It is either an enhancement or we should close the issue.
