### ISSUE TITLE
Alias "build -w" with "dev" command

### ISSUE THREAD

**Issue by rishson** [dojo/cli#14]
Implement the `run` command:

```
[inside the application dir]
dojo run

Running [app name] on http://localhost:[somePort]

[any important run info goes here, e.g. when a watch detects changes, recompilation errors]
```

**Comment by rishson** [comment]
We should offer a `port` option so you can specify the port to run the app on.

**Comment by rishson** [comment]
As an initial implementation, could we simply do something like:

```
import static from 'node-static';
import projectNavigator from './projectNavigator';

const rootDir = projectNavigator.getRootDir();
const fileServer = new static.Server(rootDir);

require('http').createServer(function (request, response) {
    request.addListener('end', function () {
        fileServer.serve(request, response);
    }).resume();
}).listen(8080);

```

where `projectNavigator` is just a module that centralises dojo project conventions, e.g. where out `index.html` will be placed after a `build` cli task is run.

**Comment by rishson** [comment]
I'm keen to get `run` up and running asap so we could use in `todoMVC` etc..

**Comment by matt-gadd** [comment]
basically this is dealt with via the `dojo build` command, we can alias it to `run` or whatever (we don't have the capability yet), but no we're not going to build a half way house that is a basic http server, because it doesn't do what the user expects (your app wouldn't work without transpiling).

**Comment by rishson** [comment]
I was assuming that `build` would be run by other tasks, e.g. Wouldn't `run` make sure `build` was done before serving? A constant `watch` on a dir and serving is different from *just* compiling - no? Wouldn't `test` make sure `build` was done before running integration tests etc?

**Comment by agubler** [comment]
That is all included in `build` - building / watching / serving - you don't "have" to watch and serve, it is an option that i believe will be aliased to `dev`.

**Comment by matt-gadd** [comment]
`test` would run `build`, but as an example intern itself `serves` for you and given there is no point in serving something that is not runnable on it's own it may as well be coupled to the build task as an option.

**Comment by rishson** [comment]
so `run` would just be an alias to `build -serve` or similar?

**Comment by agubler** [comment]
well currently I believe that would be `dev`

**Comment by rishson** [comment]
OK `dev` is nice too.

**Comment by matt-gadd** [comment]
currently there are just `--watch` (which serves also), and `--port` switches on `dojo build`, with a view to aliasing those to `dojo dev` or `dojo run`, but we need to work out how we want the cli to support commands that can provide to multiple groups (in this case `build, dev|run`)

**Comment by rishson** [comment]
OK - sound good. I guess `watch` will always `serve` or else why are you watching right.

**Comment by rishson** [comment]
Going to rename this issue to `dev` command which is just an alias for `dojo build -w`

**Comment by agubler** [comment]
All the capabilities discussed here are covered in the two build commands `cli-build-app` and `cli-build-widget`. As for aliasing, I think that possibly we could add the support to alias commands & specific options via the `.dojorc` in the future but in the meantime consumers can do the same using `npm script`. Closing this issue, we will possibly raise a new issue that specifically covers aliasing.
