### ISSUE TITLE
Feature Request : Support JSX

### ISSUE THREAD

**Issue by sebilasse** [dojo/cli#144]
Wondered how my "html preferring" users could write dojo2 widgets in a declarative way and just read https://medium.com/maquette-news/maquette-2-2-now-supports-jsx-7da7b0a1dc98
This is so nice. I could think of a great benefit for dojo users.

**Comment by dylans** [comment]
We have support for this in a branch on one of our contributor's repos. While we think jsx is a step in the wrong direction compared to hyperscript with regards to functional reactive programming, and we're trying to avoid the temptation of supporting too many different ways of doing things (which can lead to more complexity), we will reconsider adding this as option before the release of Dojo 2.

**Comment by dylans** [comment]
I'm going to move this issue to widget-core since that is where it would be supported

**Comment by dylans** [comment]
Issue moved to [dojo/widget-core #469](https://github.com/dojo/widget-core/issues/469) via [**ZenHub**](https://www.zenhub.com/)
