### ISSUE TITLE
Explicitly design .dojorc

### ISSUE THREAD

**Issue by kitsonk** [dojo/cli#158]
**Enhancement**

We need to do a better job of managing the design of `.dojorc`.  There are a couple things we need to consider doing:

* Ensure that every option of every command is expressible in `.dojorc`.
* Design our command configuration for `.dojorc` first and figure out the right flags to allow on the command line.
* Fully document the `.dojorc` structure and options.
* Create the right API to abstract away commands from combining CLI flags and `.dojorc` configuration.

**Comment by agubler** [comment]
I think all these points have now been covered.

1) The .dojorc is documented for each of the command (in their READMEs) the can leverage it.
2) All command options can be configured in the .dojorc
3) The cli combines the .dojorc options and command line options before passing them to the commands.
