### ISSUE TITLE
Support .dojorc config via package.json

### ISSUE THREAD

**Issue by matt-gadd** [dojo/cli#160]
Supporting config via a key'd object in the `package.json` seems to be fairly common across the ecosystem now, perhaps we should consider supporting it?

**Comment by kitsonk** [comment]
[yargs](https://github.com/yargs/yargs/blob/master/docs/advanced.md#providing-configuration-in-your-packagejson) supports it... I would say we should support it.

**Comment by kitsonk** [comment]
Removing discussion, because we should do this.  Scheduling for beta5.

**Comment by kitsonk** [comment]
The solution should abstract all commands from touching the configuration, which would address the concerns in #173

**Comment by agubler** [comment]
fix in https://github.com/dojo/cli/pull/260
