### ISSUE TITLE
Installing @dojo/cli results in broken tool

### ISSUE THREAD

**Issue by rhpijnacker** [dojo/cli#172]
**Bug**

Installing @dojo/cli results in broken tool.

Package Version: 0.1.0

**Code**

λ node --version
v6.11.2

λ npm install -g @dojo/cli
+ @dojo/cli@0.1.0
added 503 packages in 39.141s

λ dojo
Commands are not available: SyntaxError: Failed to load module C:/Program Files/nodejs/node_modules/@dojo/cli/commands/eject.js
Nested error: Unexpected token { in JSON at position 68

**Comment by kitsonk** [comment]
This is likely due to an invalid `.dojorc`... can you please provide the `.dojorc` associated with this.  We agree it is not a desirable or useful error message at the moment.

**Comment by rhpijnacker** [comment]
You are correct. Renaming the file to .json made my editor highlight the error.
(Something to consider for future errors I am sure to make?)

Sorry for the noise.
