### ISSUE TITLE
eject Command should not load its configuration directly

### ISSUE THREAD

**Issue by kitsonk** [dojo/cli#173]
**Enhancement**

`eject` directly `require`s the `.dojorc`.  It should use the helper like other commands.

Refs: #172

**Comment by agubler** [comment]
Is this possible as the helper will only give the section of `.dojorc` for the command that is using the helper, but the `eject` command needs to add entries to the _other_ commands' sections?

**Comment by kitsonk** [comment]
Possibly, but there should still be an abstraction for it, especially if we move to allowing it to be added to the `package.json` right?

**Comment by agubler** [comment]
We should certainly be more graceful in handling errors loading the `.dojorc`, I imagine the change to allow using the `package.json` would be an issue of its own.

**Comment by agubler** [comment]
And we have an issue open specifically for that change https://github.com/dojo/cli/issues/160

**Comment by kitsonk** [comment]
Closing in favour of #160
