### ISSUE TITLE
Remove any bundled commands from cli

### ISSUE THREAD

**Issue by matt-gadd** [dojo/cli#183]
** Enhancement**

At the moment, it's kind of confusing to an end user (and even our own devs) that we ship `@dojo/cli-create-app` by default simply as a bootstrap, but don't ship any other commands. It also kind of obscures the fact that `@dojo/cli` is just a command runner, and that users have to install commands separately in the future.

I think we should remove any bundled commands, at the expense of one extra `npm install` call for the end user for the consistency. When we have no commands installed we should clearly let them know that they need to install a command. Something like:

> looks like you have no commands installed! want to get going quick? npm install `@dojo/cli-create-app` to scaffold your first dojo 2 app.

In the future we could also do with improving the discoverability of our commands by suggesting/showing any `cli-*` packages in the `@dojo` namespace.

**Comment by matt-gadd** [comment]
I also feel like this text is extremely confusing:

```
If a non-builtin command (e.g. build) appears missing from the command list,
please ensure it is listed in package.json and correctly installed.
```

what's a non built in command? really `init`, `eject` and `version` aren't commands anyway and are just functions of the cli and we should move them out of the command list and change this text.

**Comment by agubler** [comment]
@tomdye I believe the changes for command discovery has addressed this issue. If so can you close it out please.
