### ISSUE TITLE
Improve command discoverability

### ISSUE THREAD

**Issue by matt-gadd** [dojo/cli#184]
**Enhancement**

This kind of continues on from https://github.com/dojo/cli/issues/183, and I think it has been mentioned elsewhere (I think in regards to the create-theme functionality). We need to improve the discoverability of what commands are available for the end user to install. There are multiple ways we can attack this, a few ideas:

* list all of our commands available in `@dojo/cli-*` in when you run `dojo`, regardless of whether they are actually installed (with some different formatting/text, to let the user know they need to install them)

* have a separate command like `dojo list` or similar which shows packages that are available to download from `@dojo/cli-*`

* show some suggestion text that varies every time `dojo` is called like "have you tried @dojo/cli-create-theme?, it lets you scaffold themes quickly"

* if running a command that doesn't exist, ie `dojo build`, ask them if they have installed it and offer them suggestions what package that might be.

**Comment by umaar** [comment]
Extra thoughts: 

For a Dojo 2 app, notice commands are installed separately e.g.

```
"@dojo/cli-build-webpack": "~0.2.0"
"@dojo/cli-test-intern": "~0.2.0"
```

So three questions:

1. When we release a new command, how should the user know to install it?
2. When we update an existing command, how should the user know to update it?
3. Could it come across as unintuitive that users must install + update each command separately? 

To me this is not obvious and even if it was specified in the readme, I would forget this! I think it's better if the user only has to install a single `cli` dep and updating that automatically gives access to all new + updated CLI commands.

**Comment by tomdye** [comment]
Having discussed this with the Dojo 2 team we feel that the best approach is to:

- No longer bundle `cli-create-app` with the `cli`
- To display a list of available commands when you run `dojo`
- To indicate what can be installed with instructions and inform the user which commands can be updated.
