### ISSUE TITLE
Installing and updating CLI commands

### ISSUE THREAD

**Issue by umaar** [dojo/cli#186]
**Enhancement** 

For a Dojo 2 app, notice commands are installed separately e.g.

```
"@dojo/cli-build-webpack": "~0.2.0"
"@dojo/cli-test-intern": "~0.2.0"
```

So three questions:

1. When we release a new command, how should the user know to install it?
2. When we update an existing command, how should the user know to update it?
3. Could it come across as unintuitive that users must install + update each command separately? 

To me this is not obvious and even if it was specified in the readme, I would forget this! I think it's better if the user only has to install a single `cli` dep and updating that automatically gives access to all new + updated CLI commands.

**Comment by umaar** [comment]
I think this is similar to https://github.com/dojo/cli/issues/184

**Comment by matt-gadd** [comment]
@umaar can we just add to that issue to track?

**Comment by umaar** [comment]
Done!
