### ISSUE TITLE
Version command shows same version for all group entries

### ISSUE THREAD

**Issue by tomdye** [dojo/cli#196]
**Bug** 

Package Version: latest

When you have multiple commands at different versions under a group, ie. `cli-create-app@0.3.0` and `cli-create-theme@0.1.0` they both show the same version number .

ie. output shows `0.3.0` for both `create app` and `create theme`

**Comment by JamesMilnerUK** [comment]
I'd be interested to know if this is still happening with using `libnpmsearch` instead of `execa`.

**Comment by agubler** [comment]
This is no longer an issue.
