### ISSUE TITLE
README review

### ISSUE THREAD

**Issue by jason0x43** [dojo/cli#204]
## Notes

The subsections below refer to sections in the readme.

### (General notes)

Standardize on CLI or cli. Also, are we using "cli" as a name or a description? (So is it "the cli" or just "cli" everywhere?)

> The CLI is the officially supported way...

Maybe _This package is the officially supported way..._ or _`cli` is the officially supported way..._

### Why use

> It is designed to save you time, by promoting a standardised workflow, and automating away more mundane boilerplate tasks.

Remove the commas.

> ...multiple tools such as Webpack, Intern and tslint, you can...

[webpack](https://webpack.js.org/branding/#the-name) should be lower-cased.

> When you eject, all the configuration and build dependencies of the included tools will be moved into your project. If you are adept at configuring these tools, then you can now do so without the cli using its defaults.

Maybe _When you eject, all the configuration and build dependencies of the included tools will be moved into your project. The development process can then be tailored to the specific needs of your project._

### Usage

> Getting the cli

Remove this.

> ...then please re-install and make sure the installation runs without errors.

This might be better worded as "verify that the installation runs" or "check that the installation runs".

### Features

This section is kind of confusing. It might be clearer if "group" and "command" were renamed to "command" and "subcommand", which is a more common terminology. (Even if the group isn't technically a "command", it looks and feels like a command to the user.) Then drop the first few paragraphs and just start at "The CLI has the following built-in options:". Also, prefer "built-in" to "in-built".

> The CLI has the following in-built groups:

_The CLI has the following built-in commands_

In the paragraph listing the built-in commands, put them in a list (one per line or bulleted).

> To use them, you must install them separately, e.g.
>
> npm i @dojo/cli-build-webpack

This paragraph has a weird line break in it, and there should be a period after `npm I @dojo/cli-test-intern`.

### How do I contribute?

Would this be better as "How can I contribute?"

> An additional npm script to run prettier (with write set to true) against all src and test project files is available by running:

Maybe better worded as _You format all `src` and `test` project files by running:_

> In order to build the project run grunt dev or grunt dist.

It would be nice to add npm scripts for these tasks to the package.json and reference those instead. (This goes for the testing commands, too).

> Test cases MUST be written using Intern using the Object test interface and Assert assertion interface.

_using the "object" test interface and "assert" assertion interface_

**Comment by agubler** [comment]
If we want to update the "How do I contribute" section (I think these suggestions are good), we would need to do it across all the packages!

**Comment by agubler** [comment]
Just going to tack an extra thing here, we should mention that now the CLI will show all @dojo cli commands even if they are not installed. When a user tries to use a command that is not installed, it will direct the user to run the relevant `npm install`

**Comment by jason0x43** [comment]
It might be good to just link the contribution and testing sections for all the subproject back to the main CLI README, because there's a lot of repetition across them.

**Comment by agubler** [comment]
We could actually do that across all our repos I think! Maybe link back to meta!
