### ISSUE TITLE
README Review

### ISSUE THREAD

**Issue by edhager** [dojo/cli#205]
- The TOC does not include all of the headings.
- Under "The CLI has the following in-built groups:", put each dojo command in a bullet so it is easier to scan the document and find that list.
  - dojo create - provides scaffolding for new Dojo 2 projects. 
  - dojo eject - allows users to configure and run command instead of the cli. 
  - dojo version - provides information on the versions of installed commands and the cli itself.
- There's a warning about ejecting but no real explanation of how it works.  We should describe where the configuration files are placed and give example of ejecting, modifying a config and running the tool.  
- Is this really true about ejecting?  "This action is one-way and you cannot go back to having the tools managed by the cli."  If I eject, can't I still run the cli commands?  It just will not use the ejected config files right?

**Comment by agubler** [comment]
> - Under "The CLI has the following in-built groups:", put each dojo command in a bullet so it is easier to scan the document and find that list.
>  - dojo create - provides scaffolding for new Dojo 2 projects. 
>  - dojo eject - allows users to configure and run command instead of the cli. 
>  - dojo version - provides information on the versions of installed commands and the cli itself.

We should remove `dojo create` as `cli-create-app` is no longer bundled with the `CLI`

> - There's a warning about ejecting but no real explanation of how it works.  We should describe where the configuration files are placed and give example of ejecting, modifying a config and running the tool.  

👍 

> - Is this really true about ejecting?  "This action is one-way and you cannot go back to having the tools managed by the cli."  If I eject, can't I still run the cli commands?  It just will not use the ejected config files right?

It is true, once ejected, the commands will not be runnable through the `dojo cli`, `ejecting` should (and does I think for each of the commands) provide the command needed to run after ejection.

**Comment by edhager** [comment]
> dojo build and dojo test are not installed by default with @dojo/cli. To use them, you must install them separately, e.g. `npm i @dojo/cli-build-webpack` and `npm i @dojo/cli-test-intern` These two groups are not included by default to allow different versions of these groups to be installed per project.

@dojo/cli-build-webpack should be @dojo/cli-build-app right?
