### ISSUE TITLE
Bonus window opens up when using cli on Windows

### ISSUE THREAD

**Issue by rorticus** [dojo/cli#223]
When using cli on windows I noticed that an extra console window would open up briefly with the title `npm` and then close and the command would continue on.

At the time I was running `npm run build`.

**Comment by devpaul** [comment]
Here it is:

![capture](https://user-images.githubusercontent.com/331431/45503220-0afb6080-b73b-11e8-80ae-9a298a7d50df.PNG)

I think it's related to the cli's query to npm because it happens when nothing else is installed

**Comment by JamesMilnerUK** [comment]
It's probably the `execa` call which we removed in favour of `libnpmsearch`. Can you confirm this js still happening on master @devpaul @rorticus?

**Comment by agubler** [comment]
@JamesMilnerUK This has indeed been resolved.
