### ISSUE TITLE
.dojorc validation

### ISSUE THREAD

**Issue by JamesMilnerUK** [dojo/cli#241]
**Enhancement**

Some CLI tools that rely on configs will do validation on those configs to ensure they are correct. For example Webpack does this:

![screenshot_20180710_141137](https://user-images.githubusercontent.com/8822075/42511978-42aca07a-844b-11e8-8917-118bf3b270d1.png)

I'm not entirely sure how this would be achieved, so I thought I'd open that up for discussion. Happy to look into implementing once there is consensus on the best approach.

**Code**

I would imagine the interface would be something like this:

`dojo validate`

or  for example 

`dojo build` 

Throws an error if  `.dojorc` doesn't match a specified schema

**Comment by mwistrand** [comment]
One option would be a dedicated `validate` command alongside a `validate` method on the `Command` interface (which is how `eject` is handled). Each cli package would specify an optional `validate` method on the `Command` object it exports, and at the very least that would be executed with `$ dojo validate`. Additionally, the command-level validate could also be executed each time the command itself is invoked (e.g., `$ dojo build` would also validate the `"build-app"` config).
