### ISSUE TITLE
dojo eject hangs on Windows 10

### ISSUE THREAD

**Issue by schontz** [dojo/cli#277]
**Bug** 

Cannot eject a project.

Package Version: 

You are currently running @dojo/cli@5.0.0

  ▹  @dojo/cli-build-app@5.0.2
  ▹  @dojo/cli-create-app@5.0.1
  ▹  @dojo/cli-test-intern@5.0.0

**Code**
```
dojo create app -n sample
cd sample
dojo eject
```

**Expected behavior:**

Project ejects.

**Actual behavior:**

After saying yes to the prompt, nothing happens and the process is hung. No CPU is being used.

```
? Are you sure you want to eject (this is a permanent operation)? Yes
```

**Comment by schontz** [comment]
Running the same command in cygwin was successful.

**Comment by agubler** [comment]
This seems to be hanging when running `globby` here, changing it to use `globby.sync` fixes the hang on windows - I'm not sure why it hangs using the promise based API (will look further into it)

https://github.com/dojo/cli/blob/3575dda7fdca25ddd01469af07eedf0f3c8d51d5/src/loadCommands.ts#L17-L23

**Comment by agubler** [comment]
EDIT: It fixes that hang but it seems to hang again later down the road.

**Comment by agubler** [comment]
@schontz What version of node are you using?

**Comment by agubler** [comment]
After some more digging this looks like it's related to https://github.com/SBoudrias/Inquirer.js/issues/767 - upgrading inquirer to the latest seems to resolves the issue.
