### ISSUE TITLE
`dojo -v` Should show version number of dojo-cli

### ISSUE THREAD

**Issue by Tomdye** [dojo/cli#34]

**Comment by rishson** [comment]
@Tomdye isnt this covered in #11?

**Comment by Tomdye** [comment]
Different issue @rishson. #11 refers to seeing the versions on installed dojo packages, this is showing the version of the `dojo-cli`

**Comment by rishson** [comment]
OK - can you also get the `cli` to output the `cli`'s version when doing `dojo version` then so you get to see all the package versions and the cli version?

**Comment by Tomdye** [comment]
yes, that will be fine
