### ISSUE TITLE
Lint Command (tslint)

### ISSUE THREAD

**Issue by tomdye** [dojo/cli#46]
As our configs are to be kept internally when creating an app, we should add a `lint` command which runs `tslint` with a recommended set of config and output the results.
This can then be used as part of other commands.

Initial thoughts:
- The `-eject` functionality will spit out the `tslint.json` file
- The initial call to `dojo lint` will check for the existence of a `tslint.json` file and call it's own `eject` command if it does not exist.

**Comment by agubler** [comment]
I don't think this is a beta blocker.

**Comment by kitsonk** [comment]
It was discussed on the design meeting 3 August that this should be part of the build tooling and not a separate command.
