### ISSUE TITLE
Linking with CLI

### ISSUE THREAD

**Issue by kitsonk** [dojo/cli#5]
Since we agreed to drop support for building packages from source, would it make sense to have a feature that allowed linking to local packages?  Either through managing `npm link` or some other logical fashion.

**Comment by rishson** [comment]
@kitsonk is this a feature for end users or more aimed at dojo contributors?

**Comment by matt-gadd** [comment]
this will be implemented in `grunt-dojo2` for now. https://github.com/dojo/grunt-dojo2/pull/31

**Comment by agubler** [comment]
closing based on the implementation in grunt-dojo2
