### ISSUE TITLE
Enhance `build` to produce layer files

### ISSUE THREAD

**Issue by rishson** [dojo/cli#59]
A lá dojo1.

**Comment by kitsonk** [comment]
Refs dojo/meta#34

**Comment by matt-gadd** [comment]
@rishson can we state the problem rather than dictating a solution. there are a variety of ways we will want to make our apps performant at build time.

**Comment by rishson** [comment]
@matt-gadd fair point. I'll create a 'performance' epic on `cli` to start discussion on what we can do to create well behaved, performant apps.

**Comment by kitsonk** [comment]
So are we keeping this open then?

As far as a user story, I would say this one is one like this:

> In complex web applications with multiple views, where certain views were in order to have a functional application, not all modules are needed to be loaded upon page load, and groups of modules, with any additional dependencies not already loaded, can be loaded efficiently.
> In Dojo 1, this was accomplished by allowing the developer to group modules into logical sets which then allowed the developer to specify "layers" to allow efficient incremental loading of code and other resources as triggered by certain actions in the application.

**Comment by agubler** [comment]
I think that this would certainly warrant being kept open as a story, maybe under the wider performance epic.

**Comment by agubler** [comment]
This should probably be moved to [cli build](https://github.com/dojo/cli-build), but with more details of the problem

**Comment by dylans** [comment]
Issue moved to [dojo/cli-build #59](https://github.com/dojo/cli-build/issues/59) via [**ZenHub**](https://www.zenhub.com/)
