### ISSUE TITLE
different command renderer?

### ISSUE THREAD

**Issue by gbaumgart** [dojo/cli#69]
hi,
after flying over the sources and cli-build I am still wondering I could use this library sometime soon with an own renderer (npm/blessed, blessed-contrib). Motivation is to get rid of typing or knowing command options. 

Since its all nicely typed and based on yargs, i won´t see much trouble for now but wanted to bug you first, sorry, I´m even considering to render my existing client ux actions with a library like this since all about some ´command´ 

Anyway, what you think, might it easy to add a renderer abstraction after all? this seems good foundation code here, again :-)

thanks,g

**Comment by dylans** [comment]
Was this closed without a response on purpose @gbaumgart ?
