### ISSUE TITLE
Documentation and Design of CLI

### ISSUE THREAD

**Issue by Tomdye** [dojo/cli#8]
# Dojo CLI

## Purpose
The purpose of the `cli` is to enable users to get up and running as quickly as possible with `dojo 2`. It will provide project scaffolding and tasks commonly used during the development lifecycle. The `cli` will work based on providing it's users with a highly opinionated project structure utilising `grunt`, `intern`, `typescript` and `stylus`.

## Install
To be installed globally via 
```
npm install -g dojo-cli
```

## Architecture
- The main module `dojo-cli` will be installed globally via `npm` and is essentially a task runner.
- The tasks will live in separate modules prefixed by `dojo-cli-`
- The `dojo-cli` module will search for tasks in the following locations:
	- `dojo-cli’s` node modules directory.
	- globally installed node_modules directory.
	- the consumer project's node_modules directory.
- This order ensures that tasks installed locally will take precedence over those which are globally installed or packaged within the cli.

## Registering Tasks
Tasks must implement the `task API`.

### Task Naming
Tasks will be implemented based on a strict package naming policy. Files will be named `dojo-cli-<task>-<subtask>`. eg. `dojo-cli-build-rjs`.

- There are no restrictions to the number or type of `tasks` and `sub-tasks` that can be registered.
- When only one `sub-task` is registered for a `task` type, it will be rolled up, ie. registering only `dojo-cli-create-app` will run when you enter `dojo create`.
- Registering multiple tasks of the same task type ie. `dojo-cli-build-webpack` and `dojo-cli-build-rjs` will generate two sub tasks under `dojo build`. They can be run with `dojo build webpack` and `dojo build rjs` respectively. Typing `dojo build` will display the list of available subtasks. ie.
```
You asked for 'build'. We found 2 'build' tasks: 'rjs' and 'webpack'.
You can run either 'dojo build rjs' or 'dojo build webpack'.
```

### Arguments
Calling a task via `dojo-cli` will call the `run` function on the specified task. Any specified arguments will be passed through to the `run` function.
```
dojo test mocha --timeout=20000 === dojo-cli-test-mocha.run({timeout: 20000}
```

### Default tasks (Not MVP)
Default tasks can be set using the `dojo config` command and are global defaults. 
This could be used to define which `subtask` is ran when there are multiple under the same `task` type. ie. `dojo config build.default rjs` would ensure that `dojo build` ran the `rjs` task rather than showing the user available options.

### `description`
Provides a description of the sub task to be displayed to the user.

### `name`
Provides a name to be displayed to the user.

### `register`
Registers the arguments that the sub task will accept and provides hints for those tasks to be displayed when `--help` is called.

### `run`
The function to be ran when the task is executed. Will be passed the command line arguments.

## Updates
The CLI will inform the user when there is an update available to the `dojo-cli` core package.
Furthermore the user should be informed of any updates to it's installed tasks

**Comment by Tomdye** [comment]
`command` or `task` ?

**Comment by rishson** [comment]
Ta @Tomdye 
Ca we have some doco around how the tasks will register with the runner as well please?

**Comment by rishson** [comment]
Also, I'd remove the `ci` task for now and rename the `package` task to `build`.

**Comment by agubler** [comment]
Yup I prefer `build` over `package`

**Comment by rishson** [comment]
Yeah - keeps it consistent with `dojo1` build.

**Comment by rishson** [comment]
Maybe also add `dojo build -dev` as a replacement for the `npm prepublish` tasks. 🐶 🍔  (thats dogfooding btw).

**Comment by matt-gadd** [comment]
`command` is a better term imo

**Comment by matt-gadd** [comment]
i like the `config` command, where would this config be stored? and what other than default commands would it store?

**Comment by Tomdye** [comment]
@matt-gadd initial thoughts from a brainstorm with @rishson were along lines of:
```
switch(process.platform) {
    case 'win32':
      dataPath = path.join(homeDir, "/dojo-cli");
      break;
    case 'darwin':
      dataPath = path.join(homeDir, "/Library/Application Support/dojo-cli");
      break;
    default:
      dataPath = path.join(homeDir, "/.local/dojo-cli");
  }
```

**Comment by rishson** [comment]
yep, where:

`const homeDir = isPosix() ? process.env.HOME : process.env.APPDATA;`

**Comment by Tomdye** [comment]
there's a package for that too.... :)

**Comment by matt-gadd** [comment]
@Tomdye lets not do anything platform specific please :). ideally we don't want to store it globally anyway, one dojo project might use one preference compared to another. how about a simple .dojorc in the project dir if they do set config.

**Comment by rishson** [comment]
Literally, the code would be:

```

function getDataDir(){

const homeDir = isPosix() ? process.env.HOME : process.env.APPDATA;
switch(process.platform) {
    case 'win32':
      dataPath = path.join(homeDir, "/dojo-cli");
      break;
    case 'darwin':
      dataPath = path.join(homeDir, "/Library/Application Support/dojo-cli");
      break;
    default:
      dataPath = path.join(homeDir, "/.local/dojo-cli");
  }
return dataPath;

function isPosix(){
  return process.platform !== 'win32';
}
}
```

**Comment by rishson** [comment]
dot files and dirs don't always work in win32

**Comment by rishson** [comment]
`dojoConfig.json` is better

**Comment by agubler** [comment]
why don't dot files always work on win32?

**Comment by rishson** [comment]
@matt-gadd - in dir would mean you have to re-set defaults for each project. The code to do xplatform is not that hard.

**Comment by matt-gadd** [comment]
lets not call it dojoConfig, that already has meaning in dojo 1 that is not equivelent

**Comment by rishson** [comment]
@agubler windows likes filename.extention

**Comment by agubler** [comment]
@matt-gadd 100% agree

**Comment by matt-gadd** [comment]
@rishson new projects get the defaults anyway..

**Comment by Tomdye** [comment]
`dojo.rc` ?

**Comment by rishson** [comment]
`dojo-cli.json`?

@matt - so we hardcode defaults when we scaffold and you can override with `git`-like config changes `dojo config some.prop someVal`?

**Comment by Tomdye** [comment]
but then we'd have to differentiate between updating local / global and even then we still ned somewhere to store the globals

**Comment by rishson** [comment]
following `git` syntax: `dojo config --global some.prop someVal`

**Comment by matt-gadd** [comment]
globals can be stored in dojo-cli i guess. there is still no need for the platform specific code. just use require as you would normally.

**Comment by rishson** [comment]
@matt-gadd how would you prevent loosing all your globals when you re-install a global node dep?

**Comment by rishson** [comment]
`npm` is being *weird* like always
`rm -rf node_modules && npm i`

**Comment by agubler** [comment]
do we need to include config for the mvp? The example given is to select a default sub task, but if the user wanted to use just a single type of "build" they would only have that dependency in the project.

**Comment by rishson** [comment]
don't need config for MVP - but I'l like it covered off in the arch doco before we start.

**Comment by matt-gadd** [comment]
completely agreed, i don't think the config is for mvp

**Comment by rishson** [comment]
MVP is: `create, help, run, test`

next is `build`

then `config`

**Comment by agubler** [comment]
Okay that's fine but we are bikeshedding on what to call the config file and exactly how we'll support global vs local config values. Probably can leave that until we get to it 😄

**Comment by agubler** [comment]
@rishson IMO `build` is MVP

**Comment by rishson** [comment]
Not sure pasting the entire code you need to do it is 'bikeshedding' 😂

**Comment by agubler** [comment]
yeah I'm sure whoever implements it will come back to that one comment and just commit it straight in 🙈

**Comment by rishson** [comment]
I don't mind `build` being in MVP - but it could take awhile @matt-gadd ?
