### ISSUE TITLE
Add verbose mode to 'dojo version'

### ISSUE THREAD

**Issue by rishson** [dojo/cli#81]
Under `--verbose` or similar, output the physical location of each installed command.
We should also update the `dojo help` text to include a section on command loading precedence (and add to the enhanced `version` command)

e.g.

```
$ dojo version -verbose

build (dojo-cli-build-webpack) 2.0.0 (global)
anothercommand (dojo-cli-another-command) 2.0.0 (/path/to/pwd/node_modules)

You are currently running dojo-cli 2.0.0

Command loading
------------------
Bit about where we look for commands and the resolution order...
```

**Comment by kitsonk** [comment]
Closing in favour of #134
