### ISSUE TITLE
cli should be able to store basic config on a per command basis

### ISSUE THREAD

**Issue by matt-gadd** [dojo/cli#88]
Although the cli commands are designed to be mostly config free, it seems like in quite a few cases some basic preferences are desirable. An example of this would be the `locale` in cli-build, or the `functional` or `unit` test modes in `cli-test`

A command would be able to persist preferences for itself via a cli setter api - which would be then stored in a `.dojorc` at the project level. The command would receive preferences on load (and/or a getter api)

**Comment by agubler** [comment]
Done via #90
