### ISSUE TITLE
Dojo CLI Commands

### ISSUE THREAD

**Issue by Tomdye** [dojo/cli#9]
# Dojo CLI Commands

### create
`dojo create <appName>`
- Creates a new folder `appName` and inits a dojo2 application within.
- Will not proceed if the folder already exists
- Does **not** guide the user with a wizard
- Scaffolds an app with recommended components

### test
`dojo test [local | remote]`
- Uses the `intern` test runner
- Optional arguments of `local` and `remote`

### run (Not MVP)
`dojo run [appName]	`
- Compiles code, starts `http` server, opens default browser
- Watches for changes and performs live reload?

### build
`dojo build`
- Performs build
	- JS
	- HTML
	- CSS
- Creates `.tgz` file?
- Builds ready for deployment?
- watch?
- serve?

### serve ??
`dojo serve`
- Runs http-server and opens browser to `index.html`

**Comment by matt-gadd** [comment]
we should probably make it clear that the commands `create`, `test`, `run` and `build` are just categories/groups and not implementations.

the description of `test` for instance is actually the description of the specific `dojo-cli-test-intern` command for instance.

**Comment by matt-gadd** [comment]
these are perhaps our initial shipping commands looking at the above:
```text
dojo-cli-create-app
dojo-cli-test-intern
dojo-cli-build-webpack/dojo-cli-build-rjs (depending on what we choose)
dojo-cli-run-app
```

the last one is interesting, as it looks like we need support for chained commands for that?

**Comment by Tomdye** [comment]
surely we'd make `build` a peer dependency or `run` ?

**Comment by matt-gadd** [comment]
given we can have `x` build tasks, we can't physically put a dep in `run`'s package.json. perhaps we need to scaffold out some basic cli utils that get passed to the command (maybe raise a separate issue?) off the top:
```
command.exists('build');
command.run('build', args);
```
